config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "addresses#new"
end

app/models/address.rb
class Address < ApplicationRecord

  validates :place_id, uniqueness: true

  belongs_to :current_weather
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current_weather.rb
class CurrentWeather < ApplicationRecord
  include HTTParty
  WEATHER_URI = 'https://api.openweathermap.org/data/2.5'
  base_uri WEATHER_URI

  def fetch_and_save_weather
    return if expires_at.present? && expires_at > Time.now
    api_key = ENV['WEATHER_KEY']
    query = {q: "#{postal_code},us", appid: api_key, units: 'imperial', exclude: 'minutely,hourly' }
    response = self.class.get('/weather', query: query)
    if response.success?
      data = response.parsed_response
      data = data.is_a?(Hash) ? data : JSON.parse(data)
      self.temp = data.dig('main', 'temp')
      self.feels_like = data.dig('main', 'feels_like')
      self.high_temp = data.dig('main', 'temp_max')
      self.low_temp = data.dig('main', 'temp_min')
      self.humidity = data.dig('main', 'humidity')
      self.wind_speed = data.dig('wind', 'speed')
      self.expires_at = 29.minutes.from_now
      self.save!
    end
    self
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
    @known_addresses = Address.includes(:current_weather).all
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)
    current_weather = CurrentWeather.find_or_create_by(postal_code: @address.postal_code) if @address.postal_code.present?
    @address.current_weather = current_weather

    respond_to do |format|
      if @address.save
        current_weather.fetch_and_save_weather
        format.html { redirect_to new_address_url, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        @known_addresses = Address.includes(:current_weather).all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:formatted_address, :postal_code, :place_id, :latitude, :longitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_address.html.haml
#address.mb-2[address]
  .container
    .row
      .col-sm-7
        = address.formatted_address
      .temps.col-sm-5.text-md-end
        .row
          / Current temperature column
          .col-md-5
            .current-temp
              ="#{address.current_weather.temp.to_i}°"

          / High, Low, and Feels Like temperatures column
          .col-md-7
            .row
              / High temperature
              .col-12
                .high-temp
                  High
                  %i.bi.bi-arrow-up
                  ="#{address.current_weather.high_temp.to_i}°"
              / Low temperature
              .col-12
                .low-temp
                  Low
                  %i.bi.bi-arrow-down
                  ="#{address.current_weather.low_temp.to_i}°"
              / Feels like temperature
              .col-12
                .feels-like-temp
                  Feels Like:
                  ="#{address.current_weather.feels_like.to_i}°"
        .expires
          Refreshes in
          = distance_of_time_in_words Time.now, address.current_weather.expires_at

app/views/addresses/_form.html.haml
#address{data: {controller: 'address-autocomplete', action: 'google-maps-callback@window->address-autocomplete#initPlaces'}}
  -# Separate the address field from the form so when the user hits enter to select
  -# the address, it doesn't submit the form.
  .field
    Address
    = text_field_tag :address, {}, { size: 30, data: { address_autocomplete_target: 'field' } }

  = form_for @address do |f|
    - if @address.errors.any?
      #error_explanation
        %h2= "#{pluralize(@address.errors.count, "error")} prohibited this address from being saved:"
        %ul
          - @address.errors.full_messages.each do |message|
            %li= message



    = f.hidden_field :formatted_address, data: {address_autocomplete_target: 'formattedAddress'}
    = f.hidden_field :postal_code, data: {address_autocomplete_target: 'postalCode'}
    = f.hidden_field :place_id, data: {address_autocomplete_target: 'placeId'}
    = f.hidden_field :latitude, data: {address_autocomplete_target: 'latitude'}
    = f.hidden_field :longitude, data: {address_autocomplete_target: 'longitude'}
    .actions
      = f.submit 'Get Weather', disabled: true, data: {address_autocomplete_target: 'submit'}

app/views/addresses/edit.html.haml
%h1 Editing address

= render 'form'

= link_to 'Show', @address
\|
= link_to 'Back', addresses_path

app/views/addresses/index.html.haml
%h1 Listing addresses

%table
  %thead
    %tr
      %th Formatted address
      %th Postal code
      %th Place
      %th Latitude
      %th Longitude
      %th
      %th
      %th

  %tbody
    - @addresses.each do |address|
      %tr
        %td= address.formatted_address
        %td= address.postal_code
        %td= address.place_id
        %td= address.latitude
        %td= address.longitude
        %td= link_to 'Show', address
        %td= link_to 'Edit', edit_address_path(address)
        %td= link_to 'Destroy', address, method: :delete, data: { turbo_method: 'delete', confirm: 'Are you sure?' }

%br

= link_to 'New Address', new_address_path

app/views/addresses/new.html.haml
%h1 Find Your Weather
.container
  .row
    .col-md-6
      = render 'form'
      = link_to 'Data', addresses_path
    .col-md-6
      = render @known_addresses

app/views/addresses/show.html.haml
%p#notice= notice

%p
  %b Formatted address:
  = @address.formatted_address
%p
  %b Postal code:
  = @address.postal_code
%p
  %b Place:
  = @address.place_id
%p
  %b Latitude:
  = @address.latitude
%p
  %b Longitude:
  = @address.longitude

= link_to 'Edit', edit_address_path(@address)
\|
= link_to 'Back', addresses_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Weather73
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    %script{async: true, defer: true, src: "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_KEY']}&libraries=places&callback=initAddressAutocomplete", data: {turbolinks_eval: false}}
  %body
    = yield